export { default as Dashboard } from "./Dashboard";
export { default as AddProduct } from "./AddProduct";
export { default as AddReview } from "./AddReview";
export { default as ManageOrders } from "./ManageOrders";
export { default as ManageProducts } from "./ManageProducts";
export { default as MyOrder } from "./MyOrder";
export { default as MyProfile } from "./MyProfile";
export { default as Payment } from "./Payment";
export { default as Users } from "./Users";
